//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetUsageRecord
    {
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public int SiteId { get; set; }
        public int BrowserId { get; set; }
        public int MacAdressId { get; set; }
    
        public virtual Browser Browser { get; set; }
        public virtual MacAdress MacAdress { get; set; }
        public virtual Site Site { get; set; }
    }
}
