//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.InternetUsageRecords = new HashSet<InternetUsageRecord>();
        }
    
        public int Id { get; set; }
        public string SiteAdress { get; set; }
    
        public virtual ICollection<InternetUsageRecord> InternetUsageRecords { get; set; }
    }
}
